sudo: false

language: java

services:
  - docker

jdk:
  - openjdk11
  - oraclejdk11

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
  - unzip -qq apache-maven-3.6.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v
  - docker pull postgres:9.5-alpine

script: mvn clean install -P all-tests

after_success: mvn coveralls:report -DrepoToken=$REPO_TOKEN

notifications:
  email:
    recipients:
      - solairerove@gmail.com
