server:
  port: 8080
datasource:
  host: 'localhost:5432'
  schema: 'velka'
  url: 'jdbc:postgresql://${datasource.host}/${datasource.schema}'
  username: 'velka_user'
  password: 'testpwd'
spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    name: 'VelkaPostgres'
    driver-class-name: 'org.postgresql.Driver'
    url: '${datasource.url}'
    username: '${datasource.username}'
    password: '${datasource.password}'
  liquibase:
    url: '${datasource.url}'
    user: '${datasource.username}'
    password: '${datasource.password}'
